pipeline:
  identifier: Build_Ngel_Castro_poolsystem_1702058675879
  name: Build poolsystem
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1702058550991
        repoName: Ngel-Castro/poolsystem
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: build application
                  spec:
                    shell: Bash
                    command: |-
                      echo hello world
                      ls -la
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
